django/tryDjango1-11/menus/urls.py
from django.conf.urls import url

from .views import (
  ItemListView,
  ItemDetailView,
  ItemCreateView,
  ItemUpdateView,
)

app_name = "menus"
urlpatterns = [
    url(r'^$', ItemListView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', ItemDetailView.as_view(), name='detail'),
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name='update'),
]

django/tryDjango1-11/muypicky/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView

from profiles.views import (
    ProfileFollowToggle, RegisterView, activate_user_view
)
from restaurants.views import (
    HomeView,
    ContactView,
    # Index,
    # RestaurantListView,
    # RestaurantDetailView,
    # restaurant_createview,
    # RestaurantCreateView,
)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),
    url(r'^about/$', TemplateView.as_view(template_name='restaurants/about.html'), name='about'),
    url(r'^contact/$', ContactView.as_view(), name='contact'),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    # url(r'^restaurants/$', Index),
    # url(r'^restaurants/$', RestaurantListView.as_view(), name='restaurants'),
    # url(r'^restaurants/create/$', restaurant_createview),
    # url(r'^restaurants/create/$', RestaurantCreateView.as_view(), name='restaurant-create'),
    # url(r'^restaurants/(?P<slug>\w+)/$', RestaurantListView.as_view()),
    # url(r'^restaurants/(?P<pk>\w+)/$', RestaurantDetailView.as_view()),
    # url(r'^restaurants/(?P<rest_id>\w+)/$', RestaurantDetailView.as_view()),
    # url(r'^restaurants/(?P<slug>[\w-]+)/$', RestaurantDetailView.as_view(),
    # name='restaurant-detail'),
    url(r'^menus/', include('menus.urls', namespace='menus')),
    url(r'^profile/', include('profiles.urls', namespace='profiles')),

]

django/tryDjango1-11/restaurants/urls.py
from django.conf.urls import url

from .views import (
  RestaurantListView,
  RestaurantDetailView,
  # restaurant_createview,
  RestaurantCreateView,
  RestaurantUpdateView,
)

app_name = "restaurants"
urlpatterns = [
    url(r'^$', RestaurantListView.as_view(), name='index'),
    # url(r'^restaurants/create/$', restaurant_createview),
    url(r'^create/$', RestaurantCreateView.as_view(), name='create'),
    # url(r'^(?P<slug>\w+)/$', RestaurantListView.as_view()),
    # url(r'^(?P<pk>\w+)/$', RestaurantDetailView.as_view()),
    # url(r'^(?P<rest_id>\w+)/$', RestaurantDetailView.as_view()),
    url(r'^(?P<slug>[\w-]+)/$', RestaurantDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', RestaurantUpdateView.as_view(), name='update'),
]

django/tryDjango1-11/menus/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

from restaurants.models import RestaurantLocation


# Create your models here.
class Item(models.Model):
    # Associations
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    restaurant = models.ForeignKey(RestaurantLocation, on_delete=models.CASCADE)
    # item stuff
    name = models.CharField(max_length=120)
    contents = models.TextField(help_text="Separate each item by comma")
    excludes = models.TextField(blank=True, null=True, help_text="Separate each item by comma")
    public = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('menus:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-updated', '-created']

    def get_contents(self):
        return self.contents.split(",")

    def get_excludes(self):
        return self.excludes.split(",")

django/tryDjango1-11/restaurants/models.py
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save, post_save
from django.urls import reverse

from .utils import unique_slug_generator
from .validators import validate_category

User = settings.AUTH_USER_MODEL


# Create your models here.
class RestaurantLocationQuerySet(models.query.QuerySet):
    def search(self, query):
        if query:
            query = query.strip()
            return self.filter(
                Q(name__icontains=query) |
                Q(location__icontains=query) |
                Q(category__icontains=query) |
                Q(item__name__icontains=query) |
                Q(item__contents__icontains=query)
            ).distinct()
        return self


class RestaurantLocationManager(models.Manager):
    def get_queryset(self):
        return RestaurantLocationQuerySet(self.model, using=self._db)

    def search(self, query):
        return self.get_queryset().search(query)


class RestaurantLocation(models.Model):
    name = models.CharField(max_length=120)
    location = models.CharField(max_length=120, null=True, blank=True)
    category = models.CharField(max_length=120, null=True, blank=False,
                                validators=[validate_category])
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # my_date_time = models.DateTimeField(auto_now=False, auto_now_add=False)
    slug = models.SlugField(null=True, blank=True)
    owner = models.ForeignKey(User, on_delete=models.PROTECT)  # Django Models Unleashed JOINCFE.com

    objects = RestaurantLocationManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        # return f"/restaurants/{self.slug}"
        return reverse('restaurants:detail', kwargs={'slug': self.slug})

    @property
    def title(self):
        return self.name  # obj.title


def rl_pre_save_receiver(sender, instance, *args, **kwargs):
    # print('saving...')
    # print(instance.created)
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


# def rl_post_save_receiver(sender, instance, created, *args, **kwargs):
#   print('saved')
#   print(instance.created)
#   if not instance.slug:
#     instance.slug = unique_slug_generator(instance)

pre_save.connect(rl_pre_save_receiver, sender=RestaurantLocation)

# post_save.connect(rl_post_save_receiver, sender=RestaurantLocation)

django/tryDjango1-11/restaurants/forms.py
from django import forms

from .models import RestaurantLocation
from .validators import validate_category

class RestaurantCreateForm(forms.Form):
  name = forms.CharField()
  location = forms.CharField(required=False)
  category = forms.CharField(required=False)

class RestaurantLocationCreateForm(forms.ModelForm):
  category = forms.CharField(required=False, validators=[validate_category])
  class Meta:
    model = RestaurantLocation
    fields = [
      'name',
      'location',
      'category',
    ]

django/tryDjango1-11/restaurants/views.py
# import code; code.interact(local=dict(globals(), **locals()))
# import ipdb; ipdb.set_trace() # pipenv install ipdb

import random

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render
from django.template.defaultfilters import register
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView

from menus.models import Item
from .forms import RestaurantLocationCreateForm
from .models import RestaurantLocation


# Create your views here.
# def Index(request):
#   template_name = 'restaurants/index.html'
#   queryset = RestaurantLocation.objects.all()
#   context = {
#     "restaurant_list": queryset,
#   }
#   return render(request, template_name, context)

class RestaurantListView(LoginRequiredMixin, ListView):
    template_name = 'restaurants/index.html'

    def get_queryset(self):
        # print(self.kwargs)
        slug = self.kwargs.get("slug")
        if slug:
            queryset = RestaurantLocation.objects.filter(
                (Q(category__iexact=slug) |
                 Q(category__icontains=slug)) and
                Q(owner=self.request.user)
            )
        else:
            queryset = RestaurantLocation.objects.filter(owner=self.request.user)
        return queryset


class RestaurantDetailView(LoginRequiredMixin, DetailView):
    template_name = 'restaurants/detail.html'

    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)

    # def get_context_data(self, *args, **kwargs):
    #   print(self.kwargs)
    #   context = super(RestaurantDetailView, self).get_context_data(*args, **kwargs)
    #   print(context)
    #   return context

    # def get_object(self, *args, **kwargs):
    #   print(self.kwargs)
    #   rest_id = self.kwargs.get('rest_id')
    #   obj = get_object_or_404(RestaurantLocation, id=rest_id) # pk=rest_id
    #   return obj


class RestaurantCreateView(LoginRequiredMixin, CreateView):
    form_class = RestaurantLocationCreateForm
    template_name = 'form.html'
    success_url = "/restaurants/"
    login_url = '/login/'

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.owner = self.request.user
        return super(RestaurantCreateView, self).form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super(RestaurantCreateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Add Restaurant'
        return context


# @login_required(login_url='/login/')
# def restaurant_createview(request):
#   form = RestaurantLocationCreateForm(request.POST or None)
#   errors = None
#   if form.is_valid():
#     if request.user.is_authenticated():
#       instance = form.save(commit=False)
#       # customize
#       # like a pre_save
#       instance.owner = request.user
#       instance.save()
#       # like a post_save
#       return HttpResponseRedirect("/restaurants/")
#     else:
#       return HttpResponseRedirect("/login/")

#   if form.errors:
#     errors = form.errors

#   template_name = 'restaurants/form.html'
#   context = {
#       'form': form,
#       'errors': errors
#     }
#   return render(request, template_name, context)

class RestaurantUpdateView(LoginRequiredMixin, UpdateView):
    form_class = RestaurantLocationCreateForm
    template_name = 'form.html'
    success_url = "/restaurants/"
    login_url = '/login/'

    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(RestaurantUpdateView, self).get_context_data(*args, **kwargs)
        name = self.get_object().name
        context['title'] = f'Edit Restaurant: {name}'
        return context


class HomeView(TemplateView):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated or request.user.is_following.all().count() == 0:
            num = None
            some_list = [
                random.randint(0, 100000),
                random.randint(0, 100000),
                random.randint(0, 100000)
            ]

            condition_bool_item = True
            if condition_bool_item:
                num = random.randint(0, 100000)

            context = {
                "num": num,
                "some_list": some_list
            }
            return render(request, 'restaurants/home.html', context)

        context = {}

        user = request.user
        is_following_user_ids = [x.user.id for x in user.is_following.all()]
        # qs = Item.objects.filter(user__id__in=is_following_user_ids, public=True).order_by(
        #     "-updated")

        items_exists = Item.objects.filter(
            user__id__in=is_following_user_ids,
            public=True).order_by("-updated").exists()
        # qs = RestaurantLocation.objects.all()
        qs = user.is_following.all().select_related().order_by('?')

        if items_exists and qs.exists():
            context['following_users'] = qs

        return render(request, 'restaurants/home_feed.html', context)


@register.filter
def is_public(self):
    return self.filter(public=True)


@register.filter
def is_public_exists(self):
    return self.filter(public=True).exists()


@register.filter
def items_is_public(self):
    return self.filter(item__public=True).order_by('?')[:3]


class AboutView(TemplateView):
    template_name = 'restaurants/about.html'


class ContactView(TemplateView):
    template_name = 'restaurants/contact.html'

django/tryDjango1-11/restaurants/templates/restaurants/about.html
{% extends "base.html" %}

{% block head_title %}About || {{ block.super }}{% endblock head_title %}

{% block content %}

  <h1>About page</h1>

{% endblock content %}

django/tryDjango1-11/restaurants/templates/restaurants/contact.html
{% extends "base.html" %}

{% block head_title %}Contact || {{ block.super }}{% endblock head_title %}

{% block content %}

  <h1>Contact page</h1>

{% endblock content %}

django/tryDjango1-11/restaurants/templates/restaurants/detail.html
{% extends "base.html" %}

{% block head_title %}Home || {{ block.super }}{% endblock head_title %}

{% block content %}

<h1>{{ object.name }} <small>{{ object.category }}</small></h1>
<p>{{ object.location }}</p>
<p>{{ object.created }}, Updated {{ object.updated|timesince }} ago</p>

<p><a href="{% url 'restaurants:update' object.slug %}">Edit Restaurant</a></p>

{% endblock content %}

django/tryDjango1-11/restaurants/templates/restaurants/home.html
{% extends "base.html" %}

{% block head_title %}Home || {{ block.super }}{% endblock head_title %}

{% block content %}

  <h1>Home page</h1>

  <p>This is your number: {{ num }}</p>

  {% for some_item in some_list %}
    <p>{{ some_item }}</p>
  {% endfor %}

{% endblock content %}

django/tryDjango1-11/restaurants/templates/restaurants/home_feed.html
{% extends "base.html" %}

{% block head_title %}Profile feeds || {{ block.super }}{% endblock head_title %}

{% block content %}

    {% for profile in following_users %}
        {% if profile.user.restaurantlocation_set|items_is_public %}
            <h1 class="text-center"><a
                    href="{% url "profiles:detail" profile.user.username %}">{{ profile.user.username|title }}</a>
            </h1>
            <hr>
            {% for rest in profile.user.restaurantlocation_set|items_is_public %}
                {% if rest.item_set|is_public_exists %}
                    <div class="card" style="margin-bottom: 15px;">
                        <div class="card-header">
                            <h3><b>{{ rest.title }}</b> |
                                <small><a class="text-secondary"
                                          href="{% url "profiles:detail" profile.user.username %}?q={{ rest.category }}">{{ rest.category }}</a>
                                </small>
                            </h3>
                        </div>
                        <div class="card-body">
                        {% if rest.item_set|is_public %}
                            <span><b>Menu Items:</b></span>
                            <ul>
                                {% for item in rest.item_set|is_public %}
                                    <li>{{ item.name }}</li>
                                    {% for ing in item.get_contents %}
                                        <a class="badge badge-secondary"
                                           href="{% url "profiles:detail" profile.user.username %}?q={{ ing }}">{{ ing }}</a>
                                    {% endfor %}
                                {% endfor %}
                            </ul>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endfor %}

    <div class="card" style="position: absolute; right: 5px; top: 100px;">
        <div class="card-header text-center">
            Profiles
        </div>
        <ul class="list-group list-group-flush">
            {% for profile in following_users %}

                <li class="list-group-item"><a
                        href="{% url "profiles:detail" profile.user.username %}">
                    {{ profile.user.username|title }}</a></li>
            {% endfor %}

        </ul>
    </div>

    {#{% for menu in object_list %}#}
    {#  <h3><a href="{{ menu.get_absolute_url }}"><b>{{ menu.name }}</b></a></h3>#}
    {#  {% if menu.contents %}#}
    {#    <span><b>Contents:</b></span>#}
    {#    <ul>#}
    {#      {% for item in menu.get_contents %}#}
    {#        <li>{{ item }}</li>#}
    {#      {% endfor %}#}
    {#    </ul>#}
    {#  {% endif %}#}
    {##}
    {#  {% if menu.excludes %}#}
    {#    <span><b>Excludes:</b></span>#}
    {#    <ul>#}
    {#      {% for item in menu.get_excludes %}#}
    {#        <li>{{ item }}</li>#}
    {#      {% endfor %}#}
    {#    </ul>#}
    {#  {% endif %}#}
    {#{% endfor %}#}

{% endblock content %}

django/tryDjango1-11/restaurants/templates/restaurants/index.html
{% extends "base.html" %}

{% block head_title %}Restaurants || {{ block.super }}{% endblock head_title %}

{% block content %}

<h1>My Restaurants</h1>

<p><a href="{% url 'restaurants:create' %}">Add Restaurant</a></p>

<ul>
  {% for restaurant in object_list %}
    <li><a href="{{ restaurant.get_absolute_url }}"><b>{{ restaurant.name }}</b></a>: {{ restaurant.location }}</li>
  {% endfor %}
</ul>

{% endblock content %}