django/tryDjango1-11/menus/urls.py
from django.conf.urls import url

from .views import (
  ItemListView,
  ItemDetailView,
  ItemCreateView,
  ItemUpdateView,
)

app_name = "menus"
urlpatterns = [
    url(r'^$', ItemListView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', ItemDetailView.as_view(), name='detail'),
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name='update'),
]

django/tryDjango1-11/muypicky/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView

from profiles.views import (
    ProfileFollowToggle, RegisterView, activate_user_view
)
from restaurants.views import (
    HomeView,
    ContactView,
    # Index,
    # RestaurantListView,
    # RestaurantDetailView,
    # restaurant_createview,
    # RestaurantCreateView,
)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),
    url(r'^about/$', TemplateView.as_view(template_name='restaurants/about.html'), name='about'),
    url(r'^contact/$', ContactView.as_view(), name='contact'),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    # url(r'^restaurants/$', Index),
    # url(r'^restaurants/$', RestaurantListView.as_view(), name='restaurants'),
    # url(r'^restaurants/create/$', restaurant_createview),
    # url(r'^restaurants/create/$', RestaurantCreateView.as_view(), name='restaurant-create'),
    # url(r'^restaurants/(?P<slug>\w+)/$', RestaurantListView.as_view()),
    # url(r'^restaurants/(?P<pk>\w+)/$', RestaurantDetailView.as_view()),
    # url(r'^restaurants/(?P<rest_id>\w+)/$', RestaurantDetailView.as_view()),
    # url(r'^restaurants/(?P<slug>[\w-]+)/$', RestaurantDetailView.as_view(),
    # name='restaurant-detail'),
    url(r'^menus/', include('menus.urls', namespace='menus')),
    url(r'^profile/', include('profiles.urls', namespace='profiles')),

]

django/tryDjango1-11/templates/_nav.html
{#<a href="{% url 'home' %}">Home</a>#}
{#<a href="{% url 'about' %}">About</a>#}
{#<a href="{% url 'contact' %}">Contact</a>#}
{#{% if request.user.is_authenticated %}#}
{#    <a href="{% url 'restaurants:index' %}">Restaurants</a>#}
{#    <a href="{% url 'menus:index' %}">Menus</a>#}
{#    <a href="{% url 'profiles:detail' request.user.username %}">Profile</a>#}
{#    {% if request.user.is_superuser %}#}
{#        <a href="/admin" target="_blank">Admin</a>#}
{#    {% endif %}#}
{#{% endif %}#}



<div class="m-b-1">
    <nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">Home</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item
                    {% if request.resolver_match.view_name == 'about' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'about' %}">About</a>
                </li>
                <li class="nav-item
                    {% if request.resolver_match.view_name == 'contact' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'contact' %}">Contact</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item
                        {% if request.resolver_match.view_name == 'restaurants:index' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'restaurants:index' %}">Restaurants</a>
                    </li>
                    <li class="nav-item
                        {% if request.resolver_match.view_name == 'menus:index' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'menus:index' %}">Menus</a>
                    </li>
                    <li class="nav-item
                        {% if request.resolver_match.view_name == 'profiles:list' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'profiles:list' %}">Profiles</a>
                    </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                    <li class="nav-item
                        {% if request.resolver_match.view_name == 'profiles:detail' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'profiles:detail' request.user.username %}">Profile</a>
                    </li>
                    <li class="nav-item
                        {% if request.resolver_match.view_name == 'logout' %}active{% endif %}">
                        <a class="nav-link"
                           href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% if request.user.is_superuser %}
                        <li class="nav-item
                            {% if request.resolver_match.view_name == 'admin:index' %}active{% endif %}">
                            <a id="log-in-link" class="nav-link" href="{% url 'admin:index' %}"
                               target="_blank">Admin</a>
                        </li>
                    {% endif %}
                {% else %}
                    <li class="nav-item
                        {% if request.resolver_match.view_name == 'register' %}active{% endif %}">
                        <a id="sign-up-link" class="nav-link"
                           href="{% url 'register' %}">Register</a>
                    </li>
                    <li class="nav-item
                        {% if request.resolver_match.view_name == 'login' %}active{% endif %}">
                        <a id="log-in-link" class="nav-link"
                           href="{% url 'login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

</div>

django/tryDjango1-11/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <title>{% block head_title %}MuyPicky.com{% endblock head_title %}</title>

    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
    <style>
        html, body {
            margin: 0;
            padding: 0;
        }

        body {
            padding: 70px 0;
        }
    </style>
</head>
<body>
{% include "_nav.html" %}

<div class="container">
    {% block content %}
    {% endblock content %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

django/tryDjango1-11/templates/form.html
{% extends "base.html" %}

{% block head_title %}{{ title }} || {{ block.super }}{% endblock head_title %}

{% block content %}

    <h1>{{ title }}</h1>

    {% if form.errors.non_field_errors %}
        {{ form.errors.non_field_errors }}
    {% endif %}
    <form method="POST"> {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>

{% endblock content %}